In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [16]:
df=pd.read_csv('bank.csv')

In [17]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [19]:
df.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [20]:
df.shape

(11162, 17)

In [21]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [22]:
# we need to convert 0 and 1 from yes or no using map

In [23]:
df['deposit']=df['deposit'].map({'yes':1,'no':0})

In [24]:
df

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

       deposit  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
11157        0  
11158        0  
11159        0  
11160        0  
11161        0  

[11162 rows x 17 columns]

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
# split the data into x and y

In [27]:
x=df.drop('deposit',axis=1).values

In [28]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [30]:
y=df['deposit'].values

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [31]:
def preprocessor(df):
    res_df=df.copy()
    x=list(df.select_dtypes(include='object').columns)
    for i in x:
        res_df[i]=res_df[i].astype('category')
        res_df[i]=res_df[i].cat.codes
        res_df=pd.get_dummies(res_df,columns=[i],drop_first=True)
    return res_df

In [32]:
encoded_df=preprocessor(df)
encoded_df

age  balance  day  duration  campaign  pdays  previous  deposit  job_1  \
0       59     2343    5      1042         1     -1         0        1      0   
1       56       45    5      1467         1     -1         0        1      0   
2       41     1270    5      1389         1     -1         0        1      0   
3       55     2476    5       579         1     -1         0        1      0   
4       54      184    5       673         2     -1         0        1      0   
...    ...      ...  ...       ...       ...    ...       ...      ...    ...   
11157   33        1   20       257         1     -1         0        0      1   
11158   39      733   16        83         4     -1         0        0      0   
11159   32       29   19       156         2     -1         0        0      0   
11160   43        0    8         9         2    172         5        0      0   
11161   34        0    9       628         1     -1         0        0      0   

       job_2  ...  month_5  month_6  month_7  month_8  month_9  month_10  \
0          0  ...        0        0        0        1        0         0   
1          0  ...        0        0        0        1        0         0   
2          0  ...        0        0        0        1        0         0   
3          0  ...        0        0        0        1        0         0   
4          0  ...        0        0        0        1        0         0   
...      ...  ...      ...      ...      ...      ...      ...       ...   
11157      0  ...        0        0        0        0        0         0   
11158      0  ...        0        1        0        0        0         0   
11159      0  ...        0        0        0        0        0         0   
11160      0  ...        0        0        0        1        0         0   
11161      0  ...        1        0        0        0        0         0   

       month_11  poutcome_1  poutcome_2  poutcome_3  
0             0           0           0           1  
1             0           0           0           1  
2             0           0           0           1  
3             0           0           0           1  
4             0           0           0           1  
...         ...         ...         ...         ...  
11157         0           0           0           1  
11158         0           0           0           1  
11159         0           0           0           1  
11160         0           0           0           0  
11161         0           0           0           1  

[11162 rows x 43 columns]

In [33]:
X=encoded_df.drop('deposit',axis=1)
X.columns 

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_1', 'job_2', 'job_3', 'job_4', 'job_5', 'job_6', 'job_7', 'job_8',
       'job_9', 'job_10', 'job_11', 'marital_1', 'marital_2', 'education_1',
       'education_2', 'education_3', 'default_1', 'housing_1', 'loan_1',
       'contact_1', 'contact_2', 'month_1', 'month_2', 'month_3', 'month_4',
       'month_5', 'month_6', 'month_7', 'month_8', 'month_9', 'month_10',
       'month_11', 'poutcome_1', 'poutcome_2', 'poutcome_3'],
      dtype='object')

In [34]:
x=encoded_df.drop('deposit',axis=1).values
y=encoded_df['deposit'].values

In [35]:
x

array([[  59, 2343,    5, ...,    0,    0,    1],
       [  56,   45,    5, ...,    0,    0,    1],
       [  41, 1270,    5, ...,    0,    0,    1],
       ...,
       [  32,   29,   19, ...,    0,    0,    1],
       [  43,    0,    8, ...,    0,    0,    0],
       [  34,    0,    9, ...,    0,    0,    1]], dtype=int64)

In [36]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [40]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [43]:
fit_dt=DecisionTreeClassifier(random_state=17)

In [46]:
param_dist={'max_depth': [2,3,4,5,6,7,8,9,10],
           'criterion':['gini','entropy'],
           'max_leaf_nodes':[4,6,8,10,12,14]}

In [47]:
cv_dt=GridSearchCV(fit_dt,cv=15,param_grid=param_dist)

In [48]:
cv_dt.fit(x_train,y_train)

GridSearchCV(cv=15, estimator=DecisionTreeClassifier(random_state=17),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'max_leaf_nodes': [4, 6, 8, 10, 12, 14]})

In [49]:
print('Best params using grid search :\n',cv_dt.best_params_)

Best params using grid search :
 {'criterion': 'gini', 'max_depth': 8, 'max_leaf_nodes': 14}


In [50]:
cv_dt.best_score_

0.8096040832440361

In [51]:
fit_dt.set_params(criterion='gini',max_depth=8,max_leaf_nodes=14)

DecisionTreeClassifier(max_depth=8, max_leaf_nodes=14, random_state=17)

In [52]:
fit_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=8, max_leaf_nodes=14, random_state=17)

In [53]:
y_pred=fit_dt.predict(x_test)

In [55]:
import sklearn.metrics

In [58]:
plot_confusion_matrix(fit_dt,x_test,y_test)

NameError: name 'plot_confusion_matrix' is not defined

NameError: name 'accuracy_score' is not defined

In [63]:
from sklearn.metrics import accuracy_score,classification_report

In [64]:
accuracy_rf=accuracy_score(y_test,y_pred)
accuracy_rf

0.8163905060456784

In [65]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.78      0.81      1154
           1       0.79      0.85      0.82      1079

    accuracy                           0.82      2233
   macro avg       0.82      0.82      0.82      2233
weighted avg       0.82      0.82      0.82      2233



In [66]:
y_pred_train=fit_dt.predict(x_train)

In [67]:
accuracy_score(y_train,y_pred_train)

0.8136409452346287

In [69]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82      4719
           1       0.78      0.84      0.81      4210

    accuracy                           0.81      8929
   macro avg       0.81      0.81      0.81      8929
weighted avg       0.82      0.81      0.81      8929



In [70]:
y_pred_1=cv_dt.predict(x_test)
accuracy_rf1=accuracy_score(y_test,y_pred_1)
accuracy_rf1

0.8163905060456784